---
- name: Install Elasticsearch
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    state: started
    restart_policy: always
    ports:
      - "9200:9200"
    env:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

- name: Install Logstash
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:8.10.0
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
    volumes:
      - /opt/logstash/pipeline:/usr/share/logstash/pipeline

- name: Install Kibana
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:8.10.0
    state: started
    restart_policy: always
    ports:
      - "5601:5601"
    env:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
